sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t solar7455/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true solar7455/docker-react npm run test 